services:
  app:
    build:
      context: .
      target: development
    container_name: json-to-csv-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
      - /var/www/html/node_modules
      - /var/www/html/vendor
    ports:
      - "${APP_HOST_PORT:-8000}:8000"
      - "${APP_HOST_PORT_FE:-5173}:5173"
    environment:
      - APP_ENV=${APP_ENV:-local}
      - APP_DEBUG=${APP_DEBUG:-true}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - json-to-csv-network

  db:
    image: mysql:8.0
    container_name: json-to-csv-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-secret}
      MYSQL_DATABASE: ${DB_DATABASE:-json_to_csv}
      MYSQL_USER: ${DB_USER:-json_to_csv}
      MYSQL_PASSWORD: ${DB_PASSWORD:-secret}
    ports:
      - "${DB_HOST_PORT:-3306}:${DB_PORT:-3306}"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 10
    networks:
      - json-to-csv-network

volumes:
  db_data:
    driver: local

networks:
  json-to-csv-network:
    driver: bridge
